Algoritmo "medidas"

Var
  a, b, c, areaA, areaB, AreaC : real


Inicio
  escreva ("Digite a medida A: ")
  leia(a)
  escreva ("Digite a medida B: ")
  leia(b)
  escreva ("Digite a medida C: ")
  leia(c)
  areaA <- a * a
  areaB <- a * b / 2
  areaC <- (a + b) * c / 2
  escreval ("AREA DO QUADRADO =",areaA:6:4)
  escreval ("AREA DO TRIANGULO =",areaB:6:4)
  escreval ("AREA DO TRAPEZIO =",areaC:6:4)
  
  


Fimalgoritmo